---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-92
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- config/
- spec/
- coverage/
