name: ASIS
description: 'Social media image indexing API, primarily for use with the DigitalGov Search system.'
license: null
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - image
    - search
    - GSA
    - DigitalGovSearch
contact:
    email: search@support.digitalgov.gov
