# Work around CodeClimate's inability to use Rubocop's inherit_gem directive:
# https://github.com/codeclimate/codeclimate-rubocop/issues/71#issuecomment-635055223
inherit_from:
  - https://raw.githubusercontent.com/GSA/searchgov_style/main/.default.yml

inherit_mode:
  merge:
    - Exclude

RSpec/DescribeClass:
  Exclude:
    - spec/sidekiq_cli_spec.rb

# Always omit parentheses for methods that are part of an internal DSL
# (e.g., Rake, Rails, RSpec)
Style/MethodCallWithArgsParentheses:
  Exclude:
    # Exclude files relying on Jbuilder DSL
    - app/queries/*
