Naming/AccessorMethodName:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 7
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Rails/Output:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - bin/*
Rails/HttpPositionalArguments:
  # https://github.com/bbatsov/rubocop/issues/5624
  Exclude:
    - spec/cors_spec.rb
