inherit_gem:
  searchgov_style:
    - .default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    # All Instagram-related code is deprecated and will be removed
    - /**/**/instagram**.rb

# Always omit parentheses for methods that are part of an internal DSL
# (e.g., Rake, Rails, RSpec)
Style/MethodCallWithArgsParentheses:
  Exclude:
    # Exclude files relying on Jbuilder DSL
    - 'app/queries/*'
