require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Naming/AccessorMethodName:
  Enabled: false
Layout/LineLength:
  Enabled: true
  Max: 90
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 7
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Rails/Output:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - bin/*
Layout/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  StyleGuide: '#consistent-multi-line-chains'
  Enabled: true
  VersionAdded: '0.49'
  EnforcedStyle: trailing
  SupportedStyles:
    - leading
    - trailing

Rails/HttpPositionalArguments:
  # https://github.com/bbatsov/rubocop/issues/5624
  Exclude:
    - spec/cors_spec.rb
