language: ruby
bundler_args: --without development
rvm:
  - 2.1.2
before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.2.deb && sudo dpkg -i elasticsearch-1.3.2.deb && true
  - 'echo ''script.disable_dynamic: false'' | sudo tee --append /etc/elasticsearch/elasticsearch.yml'
  - 'echo ''index.number_of_shards: 1'' | sudo tee --append /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch start
before_script:
  - cp -p config/flickr.yml.example config/flickr.yml
  - cp -p config/instagram.yml.example config/instagram.yml
addons:
  code_climate:
    repo_token: dd3e9b170ff47be380f205b8c83d4beb37f216bcb95c0681930b1b7c65d923bd