language: ruby
bundler_args: --without development
rvm:
  - 2.3.5
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.5.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.5.deb && true
  - 'printf "script:\n  inline: true\n  stored: true\n" | sudo tee --append /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch start
services:
  - redis-server
before_script:
  - cp -p config/flickr.yml.example config/flickr.yml
  - cp -p config/instagram.yml.example config/instagram.yml
addons:
  code_climate:
    repo_token: dd3e9b170ff47be380f205b8c83d4beb37f216bcb95c0681930b1b7c65d923bd
