default: &DEFAULT
  hosts:
  <% ENV.fetch('ES_HOSTS', 'localhost:9200').split(',').each do |host| %>
    - <%= host %>
  <% end %>
  user: <%= ENV['ES_USERNAME'] || 'elastic' %>
  password: <%= ENV['ES_PASSWORD'] || 'changeme' %>
  number_of_shards: 1
  log: true
  log_level: <%= ENV.fetch('ES_LOG_LEVEL', 'ERROR') %>

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

staging:
  <<: *DEFAULT

production:
  <<: *DEFAULT
  number_of_shards: 3
