development: &default
  hosts:
    - <%= ENV['ES_HOSTS'] || 'localhost:9200' %>
  user: elastic
  password: changeme
  number_of_shards: 1
  log: true
  log_level: DEBUG

test:
  <<: *default

production:
  # Changes to the production configuration must be
  # made in the cookbooks
