default: &DEFAULT
  hosts:
    - <%= ENV['ES_HOSTS'] || 'localhost:9200' %>
  user: elastic
  password: changeme
  number_of_shards: 1
  log: true
  log_level: DEBUG

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

production:
  hosts:
    - <%= ENV['ES_HOSTS'] %>
  user: <%= ENV['ES_USERNAME'] %>
  password: <%= ENV['ES_PASSWORD'] %>