development: &default
  hosts:
    - localhost
  user: ''
  password: ''
  number_of_shards: 1
  log: true
  log_level: 0

test:
  <<: *default

production:
  # Changes to the production configuration must be
  # made in the cookbooks
