development:
  secret_key_base: 3499c5e7d4b71be3dbee781ee8aa654ce212f4bd291698296edd6fb5a1b519d020bf9ec7ca730b42bebe31847805ad271641764f4c24c8883a4980b57d660275
  newrelic:
    app_name: asis (PUT YOUR NAME HERE) (<%= Rails.env %>)
    enabled: false
    host: gov-collector.newrelic.com
    license_key: newreliclicensekeygoeshere
    log_level: info

test:
  secret_key_base: 3499c5e7d4b71be3dbee781ee8aa654ce212f4bd291698296edd6fb5a1b519d020bf9ec7ca730b42bebe31847805ad271641764f4c24c8883a4980b57d660275
  newrelic:
    app_name: asis (PUT YOUR NAME HERE) (<%= Rails.env %>)
    enabled: false
    host: gov-collector.newrelic.com
    license_key: newreliclicensekeygoeshere
    log_level: info

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  newrelic:
    app_name: i14y (<%= Rails.env %>)
    enabled: <%= ENV['NEW_RELIC_ENABLED'] %>
    host: <%= ENV['NEW_RELIC_HOST'] %>
    license_key: <%= ENV['NEW_RELIC_KEY'] %>
    log_level: info
