development: &default
  namespace: oasis
  url: <%= ENV['REDIS_HOST'] || 'redis://localhost:6379/1' %>

test:
  namespace: oasis
  url: <%= ENV['REDIS_HOST'] || 'redis://localhost:6379/1' %>

production:
  # Changes to the production configuration must be
  # made in the cookbooks
