default: &DEFAULT
  namespace: oasis
  url: <%= ENV['REDIS_SYSTEM_URL'] || 'redis://localhost:6379/0' %>
  :concurrency: 5
  :queues:
    - default

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

staging:
  <<: *DEFAULT

production:
  <<: *DEFAULT
