default: &DEFAULT
  namespace: oasis
  url: <%= ENV['REDIS_HOST'] || 'redis://localhost:6379' %>
  concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
  queues:
    - [ "default", "5" ]

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

staging:
  <<: *DEFAULT

production:
  <<: *DEFAULT
