development: &default
  namespace: oasis
  redis_url: <%= ENV['REDIS_HOST'] || 'redis://localhost:6379' %>

test:
  namespace: oasis
  redis_url: <%= ENV['REDIS_HOST'] || 'redis://localhost:6379' %>

production:
  namespace: oasis
  redis_url: ENV['REDIS_HOST']
