default: &DEFAULT
  namespace: asis
  url: <%= ENV['REDIS_HOST'] || 'redis://localhost:6379/0' %>
  :concurrency: 5
  :queues:
    - [ default, '3' ]

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

staging:
  <<: *DEFAULT

production:
  <<: *DEFAULT