default: &DEFAULT
  namespace: oasis
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || '6379' %>
  :concurrency: 5
  :queues:
    - [ default, '3' ]

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

staging:
  <<: *DEFAULT

production:
  <<: *DEFAULT
